import {sculptCanopies} from './canopy.js';
import {rebuildCreature,animateCreature} from './models.js?v=0.13.0';
import * as T from './three.module.js';
import {seeded,terrain,ITEMS,PLACES,rarity,RARITIES} from './systems.js';
const atlas={wood:0,stone:1,fiber:2,hide:3,rawmeat:4,meat:5,ore:6,coal:7,copper:8,scrap:9,bandage:10,healpotion:11,speedpotion:11,invisibility:11,sword:12,bow:13,pistol:14,woodarmor:15};
export function itemArt(key){const shapes={axe:'<path d="M20 54L35 9" stroke="#9b7146" stroke-width="6"/><path d="M31 12Q48 6 55 18L50 33L26 24Z" fill="#a4b2a6" stroke="#53645b" stroke-width="2"/>',ironaxe:'<path d="M20 54L35 9" stroke="#72543a" stroke-width="6"/><path d="M31 12Q48 6 55 18L50 33L26 24Z" fill="#c4cbd0" stroke="#60716e" stroke-width="2"/>',spear:'<path d="M14 57L43 15" stroke="#927149" stroke-width="4"/><path d="M39 22L43 3L53 12Z" fill="#acb7ac"/>',arrow:'<path d="M12 54L48 13" stroke="#ae895a" stroke-width="3"/><path d="M39 17L54 5L48 25Z" fill="#b8c3b2"/><path d="M9 44L12 54L22 57" fill="none" stroke="#d2c9a4" stroke-width="5"/>',bullet:'<path d="M24 48V24Q32 4 40 24V48Z" fill="#b6a58b" stroke="#685744" stroke-width="3"/>',stonearmor:'<path d="M22 9L32 15L42 9L55 19L47 33L45 55H19L17 33L9 19Z" fill="#88938b" stroke="#3e5045" stroke-width="3"/><path d="M20 27H45M20 38H45M32 18V53" stroke="#495e50" stroke-width="3"/>'};if(shapes[key])return '<svg class="painted-item vector-item" viewBox="0 0 64 64" aria-hidden="true">'+shapes[key]+'</svg>';const n=atlas[key];return n===undefined?`<span class="drawn-fallback">${ITEMS[key].icon}</span>`:`<span class="painted-item" style="background-position:${(n%4)*100/3}% ${Math.floor(n/4)*100/3}%" aria-hidden="true"></span>`;}
export function lootFeed(loot){const host=document.getElementById('loot-feed');if(!host)return;for(const [key,n,lvl=1] of loot){const rank=rarity({key,lvl}),r=RARITIES[rank],row=document.createElement('div');row.className='loot-row';row.dataset.rarity=rank;row.style.setProperty('--loot-color',r.color);row.innerHTML=itemArt(key)+'<div class="loot-copy"><b>'+ITEMS[key].name+((ITEMS[key].tool||ITEMS[key].armor)?' +'+lvl:'')+'</b><small>'+r.symbol+' '+r.name+'</small></div><strong>+'+n+'</strong>';host.append(row);while(host.children.length>6)host.children[0].remove();setTimeout(()=>row.remove(),4800);}}

function leafCluster(pine=false){const vertices=[],colors=[],rnd=seeded(pine?28:41);for(let j=0;j<(pine?160:180);j++){const angle=rnd()*Math.PI*2,y=rnd()*2-1,rad=Math.sqrt(1-y*y)*(pine?(1-y)*.62:1);const center=new T.Vector3(Math.cos(angle)*rad,y*.8,Math.sin(angle)*rad),size=pine?.12:.15;const u=new T.Vector3(Math.cos(angle),.35,Math.sin(angle)).multiplyScalar(size),v=new T.Vector3(-Math.sin(angle),.5,Math.cos(angle)).multiplyScalar(size*.55);const ring=[];for(let k=0;k<8;k++){const t=k/8*Math.PI*2;ring.push(center.clone().addScaledVector(u,Math.cos(t)).addScaledVector(v,Math.sin(t)));}const mid=center.clone().add(new T.Vector3(0,.035,0));const c=new T.Color().setHSL(.23+rnd()*.05,.34,.34+(y+1)*.1);for(let k=0;k<8;k++)for(const p of [ring[k],ring[(k+1)%8],mid]){vertices.push(...p.toArray());colors.push(c.r,c.g,c.b);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;}
function barkTexture(){const size=128,data=new Uint8Array(size*size*4),rnd=seeded(763);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const n=Math.sin(x*.65+Math.sin(y*.05)*1.3)*16+Math.sin(x*2.1+y*.02)*8+rnd()*8;const i=(y*size+x)*4;data[i]=117+n;data[i+1]=102+n;data[i+2]=77+n;data[i+3]=255;}const t=new T.DataTexture(data,size,size);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.needsUpdate=true;return t;}
export function artDirection(world){const scene=world.scene,rnd=seeded(835),bark=barkTexture();const data=new Uint8Array(128*128*4);for(let i=0;i<128*128;i++){const v=170+rnd()*70;data[i*4]=v;data[i*4+1]=v;data[i*4+2]=v*.92;data[i*4+3]=255;}const groundTexture=new T.DataTexture(data,128,128);groundTexture.wrapS=groundTexture.wrapT=T.RepeatWrapping;groundTexture.repeat.set(55,55);groundTexture.magFilter=T.LinearFilter;groundTexture.minFilter=T.LinearMipmapLinearFilter;groundTexture.generateMipmaps=true;groundTexture.needsUpdate=true;world.land.material.map=groundTexture;world.land.material.needsUpdate=true;world.trunks.geometry=new T.CylinderGeometry(.045,1,1,11,4);world.trunks.material=new T.MeshStandardMaterial({color:'#ad9676',map:bark,bumpMap:bark,bumpScale:.12,roughness:1});
 const foliageMaterial=new T.MeshStandardMaterial({color:'#ffffff',emissive:'#29412d',emissiveIntensity:.18,vertexColors:true,side:T.DoubleSide,roughness:.88});const sway=[];for(const [o,pine]of [[world.leaves,false],[world.pines,true]]){o.geometry=leafCluster(pine);o.instanceColor=null;o.material=foliageMaterial.clone();o.material.onBeforeCompile=shader=>{shader.uniforms.forestTime={value:0};shader.vertexShader='uniform float forestTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(forestTime*1.3+position.y*3.0+instanceMatrix[3].x)*0.026; transformed.z += cos(forestTime+position.x*4.0+instanceMatrix[3].z)*0.018;');sway.push(shader.uniforms.forestTime);};o.material.customProgramCacheKey=()=> 'forest-leaves-v3';}
 const branchGeo=new T.CylinderGeometry(.035,.11,1,6),branches=new T.InstancedMesh(branchGeo,new T.MeshStandardMaterial({color:'#66553e',map:bark}),world.treeData.length*4);const d=new T.Object3D();let idx=0;for(const t of world.treeData)for(let j=0;j<4;j++){const a=j*1.57+(t.x%2),len=t.r*.85;d.position.set(t.x+Math.sin(a)*len*.5,t.y+t.h*(.62+j*.055),t.z+Math.cos(a)*len*.5);d.rotation.set(Math.cos(a)*.9,0,-Math.sin(a)*.9);d.scale.set(1,len,1);d.updateMatrix();branches.setMatrixAt(idx++,d.matrix);}branches.castShadow=true;scene.add(branches);
 // Rounded, asymmetrical canopy lobes fill the spaces behind individual leaf sprays.
 const crownGeo=new T.SphereGeometry(1,18,12);const cp=crownGeo.attributes.position;for(let i=0;i<cp.count;i++){const x=cp.getX(i),y=cp.getY(i),z=cp.getZ(i),r=1+Math.sin(x*8+y*5)*Math.cos(z*9-y*4)*.15;cp.setXYZ(i,x*r,y*r,z*r);}crownGeo.computeVertexNormals();const canopy=new T.InstancedMesh(crownGeo,new T.MeshStandardMaterial({color:'#ffffff',map:groundTexture,roughness:1}),world.treeData.length*3);idx=0;for(const t of world.treeData)for(let j=0;j<3;j++){const a=j*2.1+t.x;d.position.set(t.x+Math.sin(a)*t.r*.48,t.y+t.h*(t.pine?.76:.9)+j*.55,t.z+Math.cos(a)*t.r*.48);d.rotation.set(.2,a,.2);d.scale.set(t.r*(t.pine?.46:.63),t.r*(t.pine?.8:.53),t.r*.57);d.updateMatrix();canopy.setMatrixAt(idx,d.matrix);canopy.setColorAt(idx++,new T.Color().setHSL(.23+rnd()*.06,.32,.35+rnd()*.12));}canopy.castShadow=true;canopy.receiveShadow=true;scene.add(canopy);const canopyWind=sculptCanopies(world,canopy);
 const fern=leafCluster(false);fern.scale(.8,.28,.8);world.grass.geometry=fern;world.grass.material=new T.MeshStandardMaterial({color:'#acc882',vertexColors:true,side:T.DoubleSide,roughness:1});
 for(const a of world.animals)rebuildCreature(a);
 const motes=new T.BufferGeometry(),p=new Float32Array(160*3);for(let i=0;i<160;i++){p[i*3]=(rnd()-.5)*80;p[i*3+1]=rnd()*12;p[i*3+2]=(rnd()-.5)*80;}motes.setAttribute('position',new T.BufferAttribute(p,3));const dust=new T.Points(motes,new T.PointsMaterial({color:'#efdb9a',size:.045,transparent:true,opacity:.45,depthWrite:false}));scene.add(dust);
 return {update(dt,time,player){canopyWind(time);sway.forEach(u=>u.value=time);dust.position.set(player.x,0,player.z);dust.rotation.y=time*.005;for(const a of world.animals){animateCreature(a,dt,time);if(a.dead&&!a.artRig?.hero){if(a.artDeath===undefined)a.artDeath=0;a.artDeath=Math.min(1,a.artDeath+dt*2);a.mesh.rotation.z=Math.sin(a.artDeath*Math.PI/2)*Math.PI/2;}}}};
}
export function regionName(player){return PLACES.find(p=>Math.hypot(player.x-p.x,player.z-p.z)<p.r+8)?.name||'برّية السرو';}
