import {RANGED,reloadPose,recoilPose} from './weapon-motion.js';
import {buildViewmodel,rebuildCreature,releaseViewmodel} from './models.js?v=0.9.0';
import * as T from './three.module.js';
import {terrain,seeded,PLACES,LIMIT,MAP_LIMIT} from './systems.js';
const box=new T.BoxGeometry(1,1,1),ball=new T.SphereGeometry(1,16,10),cylinder=new T.CylinderGeometry(1,1,1,8);
const materials=new Map();
function part(g,color,x,y,z,sx,sy,sz,geo=box){if(!materials.has(color))materials.set(color,new T.MeshStandardMaterial({color,roughness:.85,flatShading:false}));const m=new T.Mesh(geo,materials.get(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);g.add(m);return m;}
export function forestPresentation(scene,camera,world){
 const rnd=seeded(9621),stations=[],sparks=[],smoke=[],root=new T.Group();camera.add(root);root.position.set(.12,-.13,-.35);root.scale.setScalar(.5);let signature='',bowString,petModel,petKey='',equipProgress=0,actionLeft=0,actionRanged=false,actionDuration=.55,actionHeavy=false,actionCombo=0,actionImpact=.23,actionKind='',drawTarget=0,drawAmount=0,reloadProgress=-1,arrowAvailable=true;
 const trail=new T.Mesh(new T.TorusGeometry(.6,.014,3,22,2.1),new T.MeshBasicMaterial({color:'#f3deb1',transparent:true,opacity:0,depthWrite:false}));trail.position.set(.35,-.1,-1);root.add(trail);
 const flash=new T.Mesh(ball,new T.MeshBasicMaterial({color:'#ffe2a2',transparent:true,opacity:0}));flash.scale.set(.12,.12,.3);flash.position.set(.48,-.22,-1.35);root.add(flash);
 const gear=new T.Group();root.add(gear);const useMesh=new T.Group();root.add(useMesh);useMesh.visible=false;part(useMesh,'#b88e68',.45,-.4,-.7,.085,.12,.085,ball);const flask=part(useMesh,'#75967a',.45,-.25,-.73,.12,.2,.12,ball);part(useMesh,'#5e4931',.45,-.07,-.73,.055,.065,.055);let useLeft=0,useKind='';useMesh.children[0].visible=false;const useHands=new T.Group();buildViewmodel(useHands,{key:'axe',lvl:1},null);useHands.remove(useHands.getObjectByName('held-axe'));useMesh.add(useHands);
 function rebuild(it,armor){const sig=(it?.key||'')+it?.lvl+(armor?.key||'')+armor?.lvl;if(sig===signature)return;signature=sig;equipProgress=0;drawTarget=0;drawAmount=0;reloadProgress=-1;if(bowString){bowString.material.dispose();}releaseViewmodel(gear);gear.clear();bowString=null;
  bowString=buildViewmodel(gear,it,armor);
  if(!['bow','pistol'].includes(it?.key)){const held=gear.getObjectByName('held-'+(it?.key||'axe')),hand=gear.getObjectByName('right-arm');if(held&&hand){const pivot=new T.Group();pivot.name='attack-pivot';pivot.position.copy(held.position);pivot.userData.home=pivot.position.clone();gear.add(pivot);held.position.sub(pivot.position);hand.position.sub(pivot.position);hand.userData.home=hand.position.clone();pivot.add(held,hand);}}

 }

 function burst(x,y,z,color='#c1b18b',n=10){for(let i=0;i<n;i++){if(sparks.length>110)break;const m=new T.Mesh(ball,new T.MeshBasicMaterial({color,transparent:true}));m.scale.setScalar(.025+rnd()*.055);m.position.set(x,y,z);scene.add(m);sparks.push({m,v:new T.Vector3((rnd()-.5)*4,rnd()*3,(rnd()-.5)*4),life:.5+rnd()*.5});}}
 for(const p of PLACES.filter(p=>p.kind==='camp')){const g=new T.Group();g.position.set(p.x,terrain(p.x,p.z),p.z);scene.add(g);const bx=p.x+5,bz=p.z+4;part(g,'#77593b',5,1,4,2.3,.18,1.2);for(const a of [-.9,.9])for(const b of [-.4,.4])part(g,'#493a28',5+a,.5,4+b,.16,1,.16);part(g,'#6c7269',5.4,1.18,4,.5,.2,.45,ball);part(g,'#b7a080',4.5,1.14,4,.35,.12,.4);stations.push({x:bx,z:bz,kind:'bench',name:'طاولة الحطّاب'});stations.push({x:p.x,z:p.z,kind:'fire',name:p.name,id:p.id});if(p.id!=='camp'){for(let j=0;j<8;j++)part(g,'#717769',Math.sin(j)*1.2,.15,Math.cos(j)*1.2,.35,.25,.35,ball);const f=part(g,'#eac17d',0,.7,0,.55,1.3,.55,new T.ConeGeometry(1,1,7));f.material=new T.MeshBasicMaterial({color:'#ffc779'});world.fires.push(f);const light=new T.PointLight('#eabc72',8,13);light.position.set(p.x,2,p.z);scene.add(light);}for(let j=0;j<8;j++){const m=new T.Mesh(ball,new T.MeshBasicMaterial({color:'#a5aca0',transparent:true,opacity:.1,depthWrite:false}));scene.add(m);smoke.push({m,x:p.x,z:p.z,phase:j/8});}}
 // Landmarks are silhouettes visible from the trails, with traversable ground around them.
 const giant=new T.Group();giant.position.set(-48,0,18);scene.add(giant);part(giant,'#4b4031',0,11,0,2.2,24,2.2,cylinder);world.collider(-48,18,2.2);for(let j=0;j<8;j++){let a=j*.785;const branch=part(giant,'#544632',Math.sin(a)*5,17+j%3,Math.cos(a)*5,.7,13,.7,cylinder);branch.rotation.z=Math.sin(a)*.85;branch.rotation.x=Math.cos(a)*.85;part(giant,'#345c44',Math.sin(a)*7,25+j%3,Math.cos(a)*7,7,5,7,ball);}
 const lake=new T.Mesh(new T.CircleGeometry(20,48),world.water.material.clone());lake.rotation.x=-Math.PI/2;lake.position.set(10,.09,-115);scene.add(lake);
 for(let side of [-1,1])for(let j=0;j<5;j++){let x=-55+side*(5+j*1.4);part(scene,'#69543a',x,.6,72,1.3,.2,3.4);part(scene,'#65533e',x,1.3,70.6,.1,1.5,.1);} // broken middle
 const tower=new T.Group();tower.position.set(118,0,-20);scene.add(tower);for(const x of [-2,2])for(const z of [-2,2]){part(tower,'#57432e',x,4,z,.4,8,.4);world.collider(118+x,-20+z,.3);}part(tower,'#776348',0,7.6,0,5,.3,5);part(tower,'#374d3e',0,10,0,4,2,4,new T.ConeGeometry(1,1,4));for(let j=0;j<12;j++)part(tower,'#917958',0,.5+j*.58,2.1,1,.08,.16);
 for(let k=0;k<3;k++){const x=-140+(k-1)*10,z=-125+(k%2)*7;for(let j=0;j<6;j++)part(scene,'#302f28',x-3,1+j*.25,z, .3,.2,6);for(let s of [-1,1])part(scene,'#292a24',x+s*3,2.1,z-3,.3,4.2,.3);world.chest(x,z,'ruin'+k,8);world.spawnAnimal('mutant',x+3,z+5,8);const archer=world.animals.at(-1);archer.archer=true;part(archer.mesh,'#94724b',.62,1.15,.2,.07,1.1,.08).rotation.x=.3;}
 for(let i=0;i<3;i++)world.spawnAnimal('chicken',-8+i*3,43+i*2,1);
 const rock=part(scene,'#73756b',-14,4,-82,2,8,2,ball);rock.rotation.z=.65;part(scene,'#666f62',-17,6,-82,4,1,2,ball);
 world.spawnAnimal('bear',153,-145,10);const guardian=world.animals.at(-1);guardian.guardian=true;guardian.mesh.scale.multiplyScalar(1.65);guardian.hp=450;guardian.homeX=153;guardian.homeZ=-145;for(let s of [-1,1]){let ant=part(guardian.mesh,'#8c9a73',s*.4,2,.55,.1,1.2,.1,cylinder);ant.rotation.z=s*.5;}world.guardian=guardian;
 const rainGeo=new T.BufferGeometry(),rainPos=new Float32Array(600*3);for(let i=0;i<rainPos.length;i+=3){rainPos[i]=(rnd()-.5)*60;rainPos[i+1]=rnd()*28;rainPos[i+2]=(rnd()-.5)*60;}rainGeo.setAttribute('position',new T.BufferAttribute(rainPos,3));const rain=new T.Points(rainGeo,new T.PointsMaterial({color:'#b9d3ca',size:.07,transparent:true,opacity:.6}));scene.add(rain);
 const flyGeo=new T.BufferGeometry(),flyPos=new Float32Array(95*3);flyGeo.setAttribute('position',new T.BufferAttribute(flyPos,3));const flies=new T.Points(flyGeo,new T.PointsMaterial({color:'#d6eeaa',size:.075,transparent:true,opacity:.85}));scene.add(flies);
 const rays=new T.Group();scene.add(rays);for(let i=0;i<9;i++){const m=new T.Mesh(new T.ConeGeometry(.8,22,4,1,true),new T.MeshBasicMaterial({color:'#e0d9ad',transparent:true,opacity:.026,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending}));m.position.set((rnd()-.5)*90,13,(rnd()-.5)*90);m.rotation.z=.4;rays.add(m);}const windLeaves=world.leaves;const leafBase=windLeaves.rotation.z;
 function pet(key,p,time){if(key!==petKey){if(petModel)scene.remove(petModel);petKey=key;petModel=new T.Group();scene.add(petModel);if(key==='wolfpet'){rebuildCreature({kind:'wolf',mesh:petModel,legs:[],x:0,z:0});petModel.scale.setScalar(.7);}if(key==='snakepet')for(let j=0;j<9;j++)part(petModel,j===0?'#abc175':'#62794f',0,.12,j*.12,.11,.1,.14,ball);if(key==='dollpet'){part(petModel,'#927258',0,.5,0,.15,.3,.1);part(petModel,'#b1a082',0,.77,0,.15,.15,.13,ball);for(const x of [-.22,.22])part(petModel,'#8d735b',x,.5,0,.2,.06,.07);}}
  if(!key)return;petModel.position.lerp(new T.Vector3(p.x+Math.cos(p.yaw)*1.3,terrain(p.x,p.z)+(key==='dollpet'?1+Math.sin(time*2)*.08:0),p.z-Math.sin(p.yaw)*1.3),.07);petModel.rotation.y=p.yaw+Math.PI;if(key==='snakepet')petModel.children.forEach((m,j)=>m.position.x=Math.sin(time*5-j*.6)*.12);
 }
 function update(dt,time,p){equipProgress=Math.min(1,equipProgress+dt*2.5);actionLeft=Math.max(0,actionLeft-dt);const arrival=1-Math.pow(1-equipProgress,3);gear.position.y=-(1-arrival)*.7;gear.rotation.x=(1-arrival)*.35;gear.rotation.z=Math.sin(time*1.4)*.008;gear.position.x=0;gear.position.z=0;gear.rotation.y=0;const swing=gear.getObjectByName('attack-pivot')||gear;if(swing!==gear){swing.position.copy(swing.userData.home);swing.rotation.set(0,0,0);}
 if(actionLeft>0){const q=1-actionLeft/actionDuration,contact=actionImpact/actionDuration,phase=q<contact?q/contact*.5:.5+(q-contact)/(1-contact)*.5,stroke=Math.sin(phase*Math.PI);
  if(actionKind==='pistol'){const kick=recoilPose(actionDuration-actionLeft);gear.rotation.x+=kick*.24;gear.position.z=kick*.16;gear.rotation.z-=kick*.055;}
  else if(actionKind==='bow'){const release=Math.exp(-(actionDuration-actionLeft)*13);gear.rotation.z-=release*.035;gear.position.z=release*.04;}
  else {const windup=q<contact?Math.sin(q/contact*Math.PI):0;swing.rotation.y+=windup*(actionCombo?-.18:.18);swing.rotation.z+=stroke*(actionCombo?1:-1)*(actionHeavy?.78:.58);swing.rotation.x-=stroke*(actionHeavy?.48:.3);swing.position.x+=stroke*(actionCombo?.1:-.1);swing.position.z-=stroke*.13;}
 }
 drawAmount+=(drawTarget-drawAmount)*(1-Math.exp(-dt*(drawTarget>drawAmount?18:30)));
 const right=gear.getObjectByName('right-arm'),left=gear.getObjectByName('left-arm');
 if(right){if(right.userData.home)right.position.copy(right.userData.home);else right.position.set(0,0,0);right.rotation.set(0,0,0);}if(left){left.position.set(0,0,0);left.rotation.set(0,0,0);}
 if(bowString){bowString.geometry.attributes.position.setZ(1,-.97+drawAmount*.58);bowString.geometry.attributes.position.setY(0,-.32-.64*(1-drawAmount*.045));bowString.geometry.attributes.position.setY(2,-.32+.69*(1-drawAmount*.045));const limb=gear.getObjectByName('bow-limb');if(limb)limb.scale.y=1-drawAmount*.045;bowString.geometry.attributes.position.needsUpdate=true;if(right)right.position.z=drawAmount*.58;
  const arrow=gear.getObjectByName('nocked-arrow');if(arrow){arrow.position.z=drawAmount*.58;arrow.visible=arrowAvailable&&!(actionKind==='bow'&&actionLeft>actionDuration*.35);}gear.rotation.y-=drawAmount*.045;
 }
 const rod=gear.getObjectByName('pistol-ramrod');if(rod)rod.visible=reloadProgress>.24&&reloadProgress<.68;
 if(reloadProgress>=0){const pose=reloadPose(reloadProgress);gear.rotation.x+=pose.lower*.58;gear.rotation.z-=pose.lower*.19;gear.position.y-=pose.lower*.2;gear.position.z+=pose.lower*.15;if(rod)rod.position.z=-1.48+pose.ram*.22;
  if(left){left.position.set(pose.reach*.94,pose.reach*.53+pose.ram*.07,-pose.reach*.37);left.rotation.z=-pose.reach*.12;}
  const hammer=gear.getObjectByName('pistol-hammer');if(hammer)hammer.rotation.x=-pose.cock*.65;
 }else {const hammer=gear.getObjectByName('pistol-hammer');if(hammer)hammer.rotation.x=actionKind==='pistol'&&actionLeft>0?-.3:0;}
 const muzzle=gear.getObjectByName('muzzle');if(muzzle){muzzle.updateWorldMatrix(true,false);flash.position.copy(root.worldToLocal(muzzle.getWorldPosition(new T.Vector3())));}
 useLeft=Math.max(0,useLeft-dt);useMesh.visible=useLeft>0;gear.visible=useLeft<=0;flask.visible=useKind==='potion';useMesh.position.y=Math.sin(useLeft*4)*.22;useMesh.rotation.z=useKind==='potion'?-Math.sin(useLeft*3)*.4:Math.sin(useLeft*4)*.12;windLeaves.rotation.z=leafBase+Math.sin(time*.6)*.0007;let weather=Math.floor(time/120)%3,night=(1-Math.cos(time/240*Math.PI))/2;const tint=new T.Color(weather===1?'#627d7b':weather===2?'#899e90':'#6f9891').lerp(new T.Color('#294c59'),night*.45);scene.background.copy(tint);scene.fog.color.copy(tint);scene.fog.density=weather===2?.018:weather===1?.012:.008;world.hemi.intensity=2.05-night*.5;world.sun.intensity=(weather===1?1.05:2.0)-night*.7;const ominous=PLACES.some(q=>['guardian','ruins','cave'].includes(q.kind)&&Math.hypot(p.x-q.x,p.z-q.z)<q.r);if(ominous){world.hemi.intensity*=.72;world.sun.intensity*=.7;scene.fog.density*=1.25;}rain.visible=weather===1;rain.position.set(p.x,0,p.z);if(rain.visible){for(let i=0;i<rainPos.length;i+=3){rainPos[i+1]-=dt*20;if(rainPos[i+1]<0)rainPos[i+1]=28;}rainGeo.attributes.position.needsUpdate=true;}for(let i=0;i<95;i++){flyPos[i*3]=p.x+Math.sin(i*6.2+time*.03)*24;flyPos[i*3+1]=1.2+Math.sin(time+i)*.5+i%4;flyPos[i*3+2]=p.z+Math.cos(i*4.3+time*.02)*24;}flyGeo.attributes.position.needsUpdate=true;smoke.forEach(s=>{const q=(time*.11+s.phase)%1;s.m.position.set(s.x+Math.sin(q*3)*q,1+q*6,s.z+q);s.m.scale.setScalar(.2+q);s.m.material.opacity=(1-q)*.12;});for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.life-=dt;s.v.y-=dt*6;s.m.position.addScaledVector(s.v,dt);s.m.material.opacity=Math.max(0,s.life);if(s.life<=0){scene.remove(s.m);s.m.material.dispose();sparks.splice(i,1);}}trail.material.opacity=Math.max(0,trail.material.opacity-dt*3);flash.material.opacity=Math.max(0,flash.material.opacity-dt*12);return ['نسيم الغابة','مطر خفيف · رؤية أقل','ضباب كثيف'][weather];}
 return {cancelAttack(){actionLeft=0;trail.material.opacity=0;flash.material.opacity=0;},enter(){equipProgress=0;},use(kind){useKind=kind;useLeft=kind==='potion'?.85:.45;},group:root,blade:{visible:true},shaft:{scale:{y:1}},rebuild,burst,stations,update,pet,attack(kind,action={}){actionDuration=action.duration||(kind==='pistol'?RANGED.pistolRecovery:kind==='bow'?RANGED.bowRecovery:.55);actionLeft=actionDuration;actionKind=kind===true?'pistol':kind;actionRanged=kind===true||kind==='pistol'||kind==='bow';actionHeavy=!!action.heavy;actionImpact=action.impact||actionDuration*.5;actionCombo=action.combo||0;if(kind===true||kind==='pistol')flash.material.opacity=1;},impact(heavy){trail.material.opacity=heavy?.85:.6;},reload(progress=-1){reloadProgress=progress;},draw(n,available=true){drawTarget=Math.max(0,Math.min(1,n));arrowAvailable=available;}};
}
export function forestAudio(){let ctx,clock=0,windGain,masterGain,mix={master:.75,sfx:.85,ambient:.6},active=true;function sound(kind='hit',volume=1){try{if(!ctx){ctx=new AudioContext();masterGain=ctx.createGain();masterGain.gain.value=mix.master;masterGain.connect(ctx.destination);const buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const d=buffer.getChannelData(0);let v=0;for(let i=0;i<d.length;i++){v=(v+Math.random()*.04-.02)*.98;d[i]=v;}const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;windGain=ctx.createGain();windGain.gain.value=.16;noise.connect(filter);filter.connect(windGain);windGain.connect(masterGain);noise.start();}if(!active)return;ctx.resume();const duration={roots:.65,wolfgrowl:.58,growl:.5,rain:.6,breath:.45,bird:.2,shot:.16,swish:.16,bowdraw:.25,bowrelease:.13,reload:.09,wood:.12,stone:.17,rare:.5,mythic:1.2,insect:.08,hurt:.18,step:.065}[kind]||.2;const g=ctx.createGain();g.gain.setValueAtTime(Math.max(.0001,.045*volume*mix[(['bird','insect','rain'].includes(kind)?'ambient':'sfx')]),ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);g.connect(masterGain);let o;if(['rain','breath','shot','wood','step','bear','hit','stone','hurt','swish','reload','growl','roots','wolfgrowl'].includes(kind)){const b=ctx.createBuffer(1,ctx.sampleRate*duration,ctx.sampleRate);let d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1);o=ctx.createBufferSource();o.buffer=b;const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=kind==='shot'?2400:kind==='swish'?1100:kind==='reload'?1900:kind==='stone'?2800:kind==='roots'?480:kind==='wolfgrowl'?190:kind==='bear'||kind==='growl'?150:kind==='rain'?800:350;if(kind==='roots')f.frequency.exponentialRampToValueAtTime(100,ctx.currentTime+duration);o.connect(f);f.connect(g);}else{o=ctx.createOscillator();o.type=kind==='bird'?'sine':'triangle';o.frequency.setValueAtTime({bowdraw:180,bowrelease:420,bird:1800,insect:3200,mythic:440,rare:620,stone:340,hurt:70,bear:45,hit:150}[kind]||220,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='bird'?2600:kind==='rare'?1100:kind==='mythic'?1600:kind==='insect'?3000:55,ctx.currentTime+duration);o.connect(g);}o.start();o.stop(ctx.currentTime+duration);}catch{}}return {sound,setMix(values){mix={...mix,...values};if(masterGain)masterGain.gain.setTargetAtTime(active?mix.master:0,ctx.currentTime,.05);},setActive(value){active=value;if(masterGain)masterGain.gain.setTargetAtTime(value?mix.master:0,ctx.currentTime,.1);},update(dt,danger,weather){clock+=dt;if(clock>3.4){clock=0;if(windGain)windGain.gain.setTargetAtTime((weather.includes('مطر')?.3:danger?.09:.16)*mix.ambient,ctx.currentTime,.8);sound(danger?'bear':'bird',danger?.3:.18);if(!danger)setTimeout(()=>sound('bird',.09),170);if(!danger)sound('insect',.09);if(weather.includes('مطر'))sound('rain',.4);}}};}
export {drawJournalMap as illustratedMap} from './journal-map.js';
