import * as T from './three.module.js';
import {terrain,seeded,PLACES} from './systems.js';
const rng=seeded(41073),up=new T.Vector3(0,1,0);
const materials=new Map();const mat=(color,extra={})=>{const key=color+JSON.stringify(extra);if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,roughness:.91,...extra}));return materials.get(key);};
const wood=mat('#60513e'),cut=mat('#b9a075'),moss=mat('#708465'),stone=mat('#626f6c'),canvas=mat('#a19470',{side:T.DoubleSide}),iron=mat('#3f504f',{metalness:.5,roughness:.47});
function put(parent,geometry,material,p,s=[1,1,1]){const m=new T.Mesh(geometry,material);m.position.fromArray(p);m.scale.fromArray(s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function beam(parent,a,b,r=.055,material=wood){const v=new T.Vector3(...b).sub(new T.Vector3(...a));const m=put(parent,new T.CylinderGeometry(r*.8,r,v.length(),9),material,new T.Vector3(...a).add(new T.Vector3(...b)).multiplyScalar(.5).toArray());m.quaternion.setFromUnitVectors(up,v.normalize());return m;}
function fernGeometry(){const verts=[],colors=[],c=new T.Color();function triangle(a,b,d,col){verts.push(...a,...b,...d);for(let j=0;j<3;j++)colors.push(col.r,col.g,col.b);}for(let f=0;f<7;f++){const angle=f*Math.PI*2/7,len=.7+(f%3)*.13;for(let j=1;j<9;j++){const t=j/9,rad=t*len,y=Math.sin(t*Math.PI*.85)*.48;for(const side of [-1,1]){const width=(1-t)*.24,dir=angle+side*.85,root=[Math.sin(angle)*rad,y,Math.cos(angle)*rad],tip=[root[0]+Math.sin(dir)*width,root[1]+.025,root[2]+Math.cos(dir)*width];c.setHSL(.24+f*.005,.27,.27+t*.16);triangle(root,[root[0]+Math.sin(angle)*.075,y+.025,root[2]+Math.cos(angle)*.075],tip,c);}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;}
export function dressForest(world){const {scene}=world,clock={value:0},dummy=new T.Object3D();
 const skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{haze:{value:new T.Color('#7d9f9b')},zenith:{value:new T.Color('#315d6a')}},vertexShader:'varying vec3 direction;void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 haze;uniform vec3 zenith;varying vec3 direction;void main(){vec3 d=normalize(direction);float h=pow(max(0.0,d.y),.65);vec3 col=mix(haze,zenith,h);float sun=pow(max(0.0,dot(d,normalize(vec3(-.5,.55,-.45)))),48.0);col+=vec3(.28,.21,.10)*sun;gl_FragColor=vec4(col,1.0);#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}' .replace(';#include',';\n#include')});
 const sky=new T.Mesh(new T.SphereGeometry(380,24,16),skyMaterial);sky.frustumCulled=false;sky.renderOrder=-10;scene.add(sky);const viewer=scene.children.find(o=>o.isCamera);
 for(const chest of world.chests){const lidGeo=new T.CylinderGeometry(.45,.45,1.35,16,1,false,0,Math.PI);lidGeo.rotateZ(Math.PI/2);chest.lid.geometry=lidGeo;chest.lid.scale.set(1,1,1);chest.lid.material=mat('#806b49',{map:world.trunks.material.map});for(const side of [-1,1]){const trim=put(chest.lid,new T.TorusGeometry(.455,.025,5,18,Math.PI),iron,[side*.46,0,0]);trim.rotation.y=Math.PI/2;trim.rotation.z=-Math.PI/2;}}
 // Soft particles and layered animated flame silhouettes replace solid cones and square specks.
 const glowData=new Uint8Array(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const i=(y*32+x)*4,d=Math.hypot((x-15.5)/15.5,(y-15.5)/15.5);glowData[i]=glowData[i+1]=glowData[i+2]=255;glowData[i+3]=Math.max(0,1-d)**2*255;}const glow=new T.DataTexture(glowData,32,32);glow.needsUpdate=true;scene.traverse(o=>{if(o.isPoints){o.material.map=glow;o.material.alphaTest=.02;o.material.needsUpdate=true;}});
 const flameMaterial=new T.ShaderMaterial({uniforms:{time:clock},transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform float time;varying vec2 vUv;void main(){float y=vUv.y;float sway=sin(y*10.0-time*6.0)*.10*y+sin(y*19.0-time*4.0)*.04;float edge=(1.0-y)*.43;float d=abs(vUv.x-.5+sway);float alpha=(1.0-smoothstep(edge-.09,edge,d))*smoothstep(0.0,.12,y)*(1.0-y*.75);vec3 color=mix(vec3(1.0,.79,.23),vec3(1.0,.15,.015),y);gl_FragColor=vec4(color,alpha*.9);}' });
 for(const f of world.fires){f.visible=false;const g=new T.Group();g.position.copy(f.position);f.parent.add(g);for(let j=0;j<3;j++){const plane=put(g,new T.PlaneGeometry(1.3,1.65),flameMaterial,[0,.03,0]);plane.rotation.y=j*Math.PI/3;plane.castShadow=false;}}
 // Ferns are concentrated around trunks and trail verges, with open walking lanes.
 world.grass.visible=false;
 const plants=[];for(let i=0;i<world.treeData.length;i+=2){const t=world.treeData[i];for(let j=0;j<3;j++){const a=rng()*6.28,r=1+rng()*2.7;plants.push({x:t.x+Math.sin(a)*r,z:t.z+Math.cos(a)*r,s:.8+rng()*.8});}}
 for(let i=0;i<210;i++){const z=-130+rng()*275,x=5*Math.sin(z*.04)+(rng()>.5?1:-1)*(3.4+rng()*1.7);if(!PLACES.some(p=>Math.hypot(x-p.x,z-p.z)<p.r*.7))plants.push({x,z,s:.8+rng()*.6});}
 const fernMat=mat('#ffffff',{vertexColors:true,side:T.DoubleSide});fernMat.onBeforeCompile=s=>{s.uniforms.forestClock=clock;s.vertexShader='uniform float forestClock;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(forestClock*1.5+instanceMatrix[3].x+position.z*2.0)*position.y*.065;');};
 const ferns=new T.InstancedMesh(fernGeometry(),fernMat,plants.length);plants.forEach((p,i)=>{dummy.position.set(p.x,terrain(p.x,p.z)+.02,p.z);dummy.rotation.set(0,rng()*6.28,0);dummy.scale.setScalar(p.s);dummy.updateMatrix();ferns.setMatrixAt(i,dummy.matrix);});ferns.receiveShadow=true;scene.add(ferns);
 // Fallen leaves give the paths a surface at walking height without thousands of objects.
 const leafShape=new T.Shape();leafShape.moveTo(0,-.11);leafShape.quadraticCurveTo(.09,0,0,.13);leafShape.quadraticCurveTo(-.09,0,0,-.11);
 const litter=new T.InstancedMesh(new T.ShapeGeometry(leafShape,4),mat('#b39a64',{side:T.DoubleSide}),2400);for(let i=0;i<litter.count;i++){const z=(rng()-.5)*250,x=5*Math.sin(z*.04)+(rng()-.5)*14;dummy.position.set(x,terrain(x,z)+.025,z);dummy.rotation.set(-Math.PI/2,0,rng()*6.28);dummy.scale.setScalar(.7+rng()*1.4);dummy.updateMatrix();litter.setMatrixAt(i,dummy.matrix);litter.setColorAt(i,new T.Color().setHSL(.09+rng()*.09,.28,.34+rng()*.18));}scene.add(litter);
 // Sculpted mossy boulders share geometry; no changes to collectible IDs or collision routes.
 const rockGeo=new T.SphereGeometry(1,16,12),rp=rockGeo.attributes.position;for(let i=0;i<rp.count;i++){const x=rp.getX(i),y=rp.getY(i),z=rp.getZ(i),n=1+Math.sin(x*5+z*4)*.12+Math.cos(y*7-z*3)*.08;rp.setXYZ(i,x*n,y*n,z*n);}rockGeo.computeVertexNormals();
 for(const r of world.resources.filter(r=>r.key==='stone'&&r.mesh)){r.mesh.geometry=rockGeo;r.mesh.material=stone;const patch=put(r.mesh,rockGeo,moss,[0,.55,0],[.82,.43,.82]);patch.castShadow=false;}
 const roots=new T.Group();scene.add(roots);for(let i=0;i<world.treeData.length;i+=5){const t=world.treeData[i];if(Math.hypot(t.x,t.z)>150)continue;for(let j=0;j<3;j++){const a=j*2.1+t.x,pts=[[t.x,t.y+.7,t.z],[t.x+Math.sin(a)*.7,t.y+.2,t.z+Math.cos(a)*.7],[t.x+Math.sin(a)*1.8,terrain(t.x+Math.sin(a)*1.8,t.z+Math.cos(a)*1.8)+.03,t.z+Math.cos(a)*1.8]];put(roots,new T.TubeGeometry(new T.CatmullRomCurve3(pts.map(p=>new T.Vector3(...p))),6,.12,6,false),wood,[0,0,0]);}}
 // Travel camp: stitched fabric, guy ropes, rolled blankets, stools and hanging lanterns.
 const warm=mat('#ffd594',{emissive:'#eeac5d',emissiveIntensity:1.4});
 function lantern(parent,x,y,z){put(parent,new T.CylinderGeometry(.13,.15,.3,8),warm,[x,y,z]);for(const side of [-1,1])beam(parent,[x+side*.12,y-.18,z],[x+side*.12,y+.18,z],.018,iron);for(const yy of [-.18,.18])put(parent,new T.CylinderGeometry(.17,.17,.035,8),iron,[x,y+yy,z]);const ring=put(parent,new T.TorusGeometry(.075,.014,6,14),iron,[x,y+.26,z]);return ring;}
 for(const p of PLACES.filter(p=>p.kind==='camp')){const g=new T.Group();g.position.set(p.x,terrain(p.x,p.z),p.z);scene.add(g);for(const side of [-1,1]){beam(g,[side*1.5,0,-8],[side*1.5,1.1,-8],.07);beam(g,[side*1.5,1.1,-8],[side*1.5,1.1,-4],.065);beam(g,[side*2.8,.03,-3],[side*1.1,1.5,-5],.012,cut);}
  beam(g,[0,0,-8.25],[0,2.65,-8.25],.065);beam(g,[0,0,-3.75],[0,2.65,-3.75],.065);beam(g,[0,2.65,-8.4],[0,2.65,-3.5],.07);lantern(g,.35,1.65,-3.8);
  const flag=new T.PlaneGeometry(2.8,1.4,12,6);flag.rotateY(Math.PI/2);const fp=flag.attributes.position;for(let i=0;i<fp.count;i++)fp.setX(i,Math.sin(fp.getY(i)*4+fp.getZ(i)*2)*.08);flag.computeVertexNormals();put(g,flag,canvas,[-1.52,1.25,-6]);
  for(let j=0;j<3;j++){const roll=put(g,new T.CylinderGeometry(.22,.22,1.3,16),mat(j%2?'#67766b':'#897b60'),[-2.6,.26,-5+j*.7]);roll.rotation.z=Math.PI/2;for(const side of [-1,1]){const strap=put(roll,new T.TorusGeometry(.226,.025,5,16),iron,[0,side*.4,0]);strap.rotation.x=Math.PI/2;}}
  for(const x of [-3,3]){put(g,new T.CylinderGeometry(.35,.4,.6,14),wood,[x,.3,1.4]);put(g,new T.CylinderGeometry(.35,.35,.035,14),cut,[x,.62,1.4]);}
 }
 // A family of slate roof tiles and porch details makes each cabin feel inhabited.
 for(const [x,z]of [[49,-4],[68,-6],[61,17],[-30,-57]]){const g=new T.Group();g.position.set(x,terrain(x,z),z);scene.add(g);for(const side of [-1,1]){beam(g,[side*1.7,0,4.3],[side*1.7,3,4.3],.1);beam(g,[side*1.7,3,4.3],[side*1.7,3.5,3.2],.07);for(let row=0;row<5;row++)for(let col=0;col<9;col++){const tile=put(g,new T.BoxGeometry(.98,.09,.92),mat(['#4c6661','#5b7067','#435953'][(row+col)%3]),[side*(.27+row*.94),5.17-row*.42,-3.6+col*.89]);tile.rotation.z=-side*.45;}const shutter=put(g,new T.BoxGeometry(.9,1.1,.07),wood,[side*2.7,2.25,3.72]);for(let j=0;j<4;j++)put(shutter,new T.BoxGeometry(.8,.025,.04),cut,[0,-.4+j*.25,.05]);}beam(g,[-1.8,3.03,4.3],[1.8,3.03,4.3],.12);lantern(g,-1.65,2.35,4.38);for(let j=0;j<3;j++)put(g,new T.BoxGeometry(2.9,.12,1),wood,[0,.06+j*.06,4.1-j*.35]);}
 // Clouds of drifting seed fluff and animated water sheen connect the whole scene.
 const ripples=[];for(let j=0;j<12;j++){const m=put(scene,new T.RingGeometry(.7,.72,40),new T.MeshBasicMaterial({color:'#c5d7bb',transparent:true,opacity:.16,side:T.DoubleSide,depthWrite:false}),[-55+(rng()-.5)*13,.185,42+rng()*59]);m.rotation.x=-Math.PI/2;ripples.push(m);}
 world.land.material.flatShading=false;world.land.material.needsUpdate=true;world.water.material.color.set('#487a78');world.water.material.roughness=.19;
 return {update(dt,time){clock.value=time;if(viewer)sky.position.copy(viewer.position);skyMaterial.uniforms.haze.value.copy(scene.fog.color);for(let i=0;i<ripples.length;i++){const q=(time*.17+i*.137)%1;ripples[i].scale.setScalar(.3+q*3);ripples[i].material.opacity=(1-q)*.18;}}};
}
